import profile from '../assets/images/SVG/profilephoto.svg'
import verify from '../assets/images/SVG/verify.svg'
import comment from '../assets/images/SVG/Commenticon.svg'
import Retweet from '../assets/images/SVG/Retweet.svg'
import share from '../assets/images/SVG/Share.svg'
import like from '../assets/images/SVG/like.svg'

export const card = [
    {
        img: profile,
        name: "Joe Bidenn",
        verify: verify,
        about: "I am giving back in the community.",
        para: "Hipster ipsum tattooed brunch I'm baby. Crucifix cliche mixtape salvia vexillologist. Kickstarter sartorial post-ironic biodiesel cold-pressed a activated subway. Af dsa kickstarter squid",
        commentimg: comment,
        comment: 28,
        Retweetimg: Retweet,
        Retweet: 5,
        like: like,
        likecount: 21,
        share: share,
    },
    {
        img: profile,
        name: "Joe Bidenn",
        verify: verify,
        about: "I am giving back in the community.",
        para: "Hipster ipsum tattooed brunch I'm baby. Crucifix cliche mixtape salvia vexillologist. Kickstarter sartorial post-ironic biodiesel cold-pressed a activated subway. Af dsa kickstarter squid",
        commentimg: comment,
        comment: 28,
        Retweetimg: Retweet,
        Retweet: 5,
        like: like,
        likecount: 21,
        share: share,
    },
    {
        img: profile,
        name: "Joe Bidenn",
        verify: verify,
        about: "I am giving back in the community.",
        para: "Hipster ipsum tattooed brunch I'm baby. Crucifix cliche mixtape salvia vexillologist. Kickstarter sartorial post-ironic biodiesel cold-pressed a activated subway. Af dsa kickstarter squid",
        commentimg: comment,
        comment: 28,
        Retweetimg: Retweet,
        Retweet: 5,
        like: like,
        likecount: 21,
        share: share,
    },
    {
        img: profile,
        name: "Joe Bidenn",
        verify: verify,
        about: "I am giving back in the community.",
        para: "Hipster ipsum tattooed brunch I'm baby. Crucifix cliche mixtape salvia vexillologist. Kickstarter sartorial post-ironic biodiesel cold-pressed a activated subway. Af dsa kickstarter squid",
        commentimg: comment,
        comment: 28,
        Retweetimg: Retweet,
        Retweet: 5,
        like: like,
        likecount: 21,
        share: share,
    },
    {
        img: profile,
        name: "Joe Bidenn",
        verify: verify,
        about: "I am giving back in the community.",
        para: "Hipster ipsum tattooed brunch I'm baby. Crucifix cliche mixtape salvia vexillologist. Kickstarter sartorial post-ironic biodiesel cold-pressed a activated subway. Af dsa kickstarter squid",
        commentimg: comment,
        comment: 28,
        Retweetimg: Retweet,
        Retweet: 5,
        like: like,
        likecount: 21,
        share: share,
    },
    {
        img: profile,
        name: "Joe Bidenn",
        verify: verify,
        about: "I am giving back in the community.",
        para: "Hipster ipsum tattooed brunch I'm baby. Crucifix cliche mixtape salvia vexillologist. Kickstarter sartorial post-ironic biodiesel cold-pressed a activated subway. Af dsa kickstarter squid",
        commentimg: comment,
        comment: 28,
        Retweetimg: Retweet,
        Retweet: 5,
        like: like,
        likecount: 21,
        share: share,
    },
]